/**
 * Regenerates src/lib/snapshot.ts from live Yahoo Finance data.
 *
 *   npm run snapshot
 *
 * The app fetches live prices at request time; this file is the committed
 * fallback so a build or a request still renders real Indian market data when
 * Yahoo is unreachable. Re-run it whenever the fallback looks stale.
 */

import { writeFileSync, mkdirSync } from "node:fs";
import { dirname } from "node:path";

const UA =
  "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0 Safari/537.36";

const OUT = "src/lib/snapshot.ts";

const INDICES = [
  ["NIFTY", "^NSEI", "NIFTY 50"],
  ["SENSEX", "^BSESN", "S&P BSE SENSEX"],
  ["BANKNIFTY", "^NSEBANK", "NIFTY Bank"],
  ["MIDCPNIFTY", "NIFTY_MID_SELECT.NS", "NIFTY Midcap Select"],
  ["FINNIFTY", "NIFTY_FIN_SERVICE.NS", "NIFTY Fin Services"],
];

const STOCKS = [
  "RELIANCE", "HDFCBANK", "INFY", "TCS", "ITC", "TMPV", "SBIN", "LT",
  "COALINDIA", "TATAPOWER", "ADANIGREEN", "HINDALCO", "PERSISTENT", "BEL",
  "DIXON", "AXISBANK", "ICICIBANK", "MARUTI", "TITAN", "SUNPHARMA", "WIPRO",
  "ONGC", "BAJFINANCE", "TATASTEEL", "SOLARINDS", "TRENT", "JSWSTEEL",
  "POWERGRID", "NTPC", "ADANIPORTS", "KOTAKBANK", "HINDUNILVR",
];

async function chart(yahoo, range) {
  const url = `https://query1.finance.yahoo.com/v8/finance/chart/${encodeURIComponent(yahoo)}?interval=1d&range=${range}`;
  const res = await fetch(url, { headers: { "User-Agent": UA } });
  if (!res.ok) throw new Error(`${yahoo} -> HTTP ${res.status}`);
  const json = await res.json();
  const result = json?.chart?.result?.[0];
  if (!result) throw new Error(`${yahoo} -> empty result`);
  return result;
}

function bars(res) {
  const ts = res.timestamp ?? [];
  const q = res.indicators?.quote?.[0] ?? {};
  const out = [];
  for (let i = 0; i < ts.length; i++) {
    const c = q.close?.[i];
    if (typeof c === "number" && Number.isFinite(c)) {
      out.push({
        d: new Date(ts[i] * 1000).toISOString().slice(0, 10),
        c: +c.toFixed(2),
        v: typeof q.volume?.[i] === "number" ? q.volume[i] : null,
      });
    }
  }
  return out;
}

async function quote(symbol, yahoo, name) {
  const res = await chart(yahoo, "3mo");
  const series = bars(res);
  const last = res.meta.regularMarketPrice ?? series.at(-1)?.c;
  if (typeof last !== "number") throw new Error(`${yahoo} -> no price`);

  // Previous close is the second-last bar for a dense series. Some derived NSE
  // index tickers have gap-ridden history on Yahoo; differencing bars two
  // months apart would report that gap as today's move, so those fall back to
  // a 1-month window where chartPreviousClose resolves correctly.
  let prev;
  if (series.length >= 2) {
    const gap = (Date.parse(series.at(-1).d) - Date.parse(series.at(-2).d)) / 86_400_000;
    if (gap <= 4) prev = series.at(-2).c;
  }
  if (prev === undefined) {
    const short = await chart(yahoo, "1mo");
    prev = short.meta.chartPreviousClose ?? short.meta.previousClose ?? last;
  }

  const vols = series.map((b) => b.v).filter((v) => typeof v === "number" && v > 0);
  const recent = vols.slice(-21, -1);
  const avgVolume = recent.length ? Math.round(recent.reduce((a, b) => a + b, 0) / recent.length) : null;

  const change = last - prev;
  return {
    symbol,
    yahoo,
    name: name ?? res.meta.shortName ?? res.meta.longName ?? symbol,
    last: +last.toFixed(2),
    prevClose: +prev.toFixed(2),
    change: +change.toFixed(2),
    changePct: +((change / prev) * 100).toFixed(2),
    dayHigh: res.meta.regularMarketDayHigh ?? null,
    dayLow: res.meta.regularMarketDayLow ?? null,
    volume: res.meta.regularMarketVolume ?? null,
    avgVolume,
    spark: series.slice(-30).map((b) => b.c),
  };
}

const indices = [];
const stocks = [];

for (const [symbol, yahoo, name] of INDICES) {
  try {
    indices.push(await quote(symbol, yahoo, name));
    console.error(`ok  ${symbol}`);
  } catch (e) {
    console.error(`ERR ${symbol}: ${e.message}`);
  }
}

for (const s of STOCKS) {
  try {
    stocks.push(await quote(s, `${s}.NS`, null));
    console.error(`ok  ${s}`);
  } catch (e) {
    console.error(`ERR ${s}: ${e.message}`);
  }
}

if (indices.length < 3 || stocks.length < 10) {
  console.error("Refusing to write a thin snapshot — leaving the existing file alone.");
  process.exit(1);
}

const payload = { fetchedAt: new Date().toISOString(), indices, stocks };

const header = [
  "/**",
  " * Committed fallback snapshot of real NSE data, pulled from Yahoo Finance.",
  " *",
  " * The app fetches live prices at request time; this exists so a build or a",
  " * request still renders real Indian market data when Yahoo is unreachable.",
  " *",
  " * Generated by scripts/snapshot.mjs — run `npm run snapshot` to refresh.",
  " * DO NOT hand-edit: every number here really traded.",
  " */",
  "",
  'import type { Quote } from "./api/yahoo";',
  "",
  "export interface Snapshot {",
  "  fetchedAt: string;",
  "  indices: Quote[];",
  "  stocks: Quote[];",
  "}",
  "",
].join("\n");

const footer = [
  "",
  "export const SNAPSHOT_STOCKS: Record<string, Quote> = Object.fromEntries(",
  "  SNAPSHOT.stocks.map((s) => [s.symbol, s]),",
  ");",
  "",
].join("\n");

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(
  OUT,
  `${header}export const SNAPSHOT: Snapshot = ${JSON.stringify(payload, null, 2)};\n${footer}`,
  "utf8",
);

console.error(`\nwrote ${OUT} — ${indices.length} indices, ${stocks.length} stocks`);
